scss modi
hiroakioike/Plofile pull request #1
Opened 2024-05-01 02:18 UTC by hiroakioike

2024-05-02 13:24 UTC, alpaca1231 reviewed
SP表示でデザインが崩れている
![image](https://github.com/hiroakioike/Profile/assets/80532711/f20592b4-d162-4298-95a5-cf927d86f636)

2024-05-02 13:33 UTC, alpaca1231 reviewed
`ul`に不要な余白が残っている（おそらくreset.cssが正しく適用されていない箇所がある）
![image](https://github.com/hiroakioike/Profile/assets/80532711/212ce0d3-4d18-44ab-bb96-5f43c4b88ab2)

2024-05-02 13:35 UTC, alpaca1231 reviewed
headerの高さが大きい

| デザイン | 実装 |
| --- | --- |
| ![image](https://github.com/hiroakioike/Profile/assets/80532711/8d42f7b8-46fe-4d6f-9a31-2899ecf979d9) | ![image](https://github.com/hiroakioike/Profile/assets/80532711/ac8b8720-f447-4517-928c-14dd2cc9949d) |

2024-05-02 14:06 UTC, alpaca1231 requested changes
いくつかコメントしました

2024-05-02 14:06 UTC, alpaca1231 commented on css/style.scss
> +#header {
基本的にはCSSでidを使ったセレクタは使用しないです
今回は良いけど今後はclassにheaderを適用してください

2024-05-02 14:06 UTC, alpaca1231 commented on css/style.scss
> +}
たぶん`.body`ではなく`body`が正しい

一応HTML要素の名前を付けたクラス名は基本的には避けるべきってことも覚えておいて

2024-05-02 14:06 UTC, alpaca1231 commented on css/style.scss
> +    ul {
HTML要素にCSS直当て警察です。
もしheaderにulが増えたらどうするんですか？

コメント付けるの省略するけど他の箇所も同様です

2024-05-02 14:06 UTC, alpaca1231 commented on css/style.scss
> +            margin-left: 30px;
この書き方だと一番左のli要素に不要な余白が発生しませんか？
こうならないCSSの書き方があるので応用編として調べてください
![image](https://github.com/hiroakioike/Profile/assets/80532711/b2e0751e-786f-4ab1-aa40-b1db6decd466)

2024-05-02 14:06 UTC, alpaca1231 commented on css/style.scss
> +}
```suggestion
#mainvisual {
    margin-bottom: 80px;
    img {
        width: 100%;
        max-width: 1920px;
        height: 600px;
        object-fit: cover;

        @media screen and (max-width: 760px) {
            height: calc(100vh - 60px);
        }
    }
}
```

好みの問題かもしれないけどこういう書き方のほうが見やすい気がする

2024-05-02 14:06 UTC, alpaca1231 commented on css/style.scss
> +        flex-direction:column
```suggestion
        flex-direction: column;
```

セミコロンがない

2024-05-02 14:06 UTC, alpaca1231 commented on css/style.scss
> +    #biccycle ul {
```suggestion
    #bicycle ul {
```

タイポ

2024-05-02 14:06 UTC, alpaca1231 commented on css/TheNewCSSReset.css
たぶん上手く適用されていないCSSがありそう

下記のサイトからコピペし直したらちゃんと適用された
https://elad2412.github.io/the-new-css-reset/

2024-05-02 14:06 UTC, alpaca1231 commented on css/TheNewCSSReset.css
ファイル名はreset.cssくらいが良さそう

ちなみに言語ごとにファイル名の命名規則は決まっていて、CSSのファイル名で[PascalCase](https://qiita.com/shota0616/items/4ac7a8696b3f6ccbe2bc#%E3%83%91%E3%82%B9%E3%82%AB%E3%83%AB%E3%82%B1%E3%83%BC%E3%82%B9pascalcase)を使うことはまずないです。
HTMLとCSSの命名規則に関しては[こちら](https://yoncoichi.com/file-name/)を参考に

2024-05-02 14:06 UTC, alpaca1231 commented on css/style.css
たぶん最後にScssを編集してから一度もコンパイルされてないかも

2024-05-08 14:17 UTC, hiroakioike commented on css/style.scss
> +    ul {
ここで一番悩んだけど結局どんな形にするのが良いのですか？
この部分だけでも教えてほしいです

2024-05-08 19:37 UTC, hiroakioike commented on css/style.css
保存して反映してというそもそもの使い方が分かってなかったかも
これでできてますかね、、、？

2024-05-08 19:38 UTC, hiroakioike commented on css/TheNewCSSReset.css
「TheNew...」の方をやめてreset.cssをコピペして作りました

2024-05-08 20:15 UTC, hiroakioike commented on css/style.scss
> +            margin-left: 30px;
padding-left:0px
ulタグに入れるで合ってますかね

2024-05-09 05:18 UTC, alpaca1231 commented on css/style.scss
> +    ul {
ulに`class="header-nav-list`みたいにclass名を付与してCSSセレクタでclassを指定する

そうすれば例えHeader内に違うulタグが増えてもclass指定しているulにしかCSSが適用されなくなる

2024-05-09 05:19 UTC, alpaca1231 commented on css/style.scss
> +            margin-left: 30px;
ulタグに当てても子要素のliタグに付いてるpaddingは消えません
ヒントを出すとliタグの1つ目はpadding-leftが0になるようにするという考え方です

2024-05-09 05:21 UTC, alpaca1231 commented on css/style.scss
> +}
これbodyだけじゃなくて`.html`や`.a`とかも全部ね

2024-05-22 05:24 UTC, hiroakioike commented on css/style.scss
> +            margin-left: 30px;
chatgpt先生にfirst-child使うんやでと教えてもらいました

2024-05-22 09:07 UTC, alpaca1231 reviewed
コード見ただけでコメントしました
実際の画面はまだ見てません

2024-05-22 09:07 UTC, alpaca1231 commented on css/TheNewCSSReset.css
要らないファイルなので消してください

2024-05-22 09:07 UTC, alpaca1231 commented on css/style.scss
> +}
この辺りの記述が必要な理由はなんですか？

2024-05-22 09:07 UTC, alpaca1231 commented on css/style.scss
> +          }
この部分のCSSは`li`の`first-child`にしか当たらなくなると思うけどええの？
最初の要素だけカラー指定？

2024-05-22 09:07 UTC, alpaca1231 commented on css/style.scss
> +      &:first-child {
いいね！

ちなみにもっとかっこよく書く方法もあるのでまた今度紹介しますね

2024-05-22 09:07 UTC, alpaca1231 commented on css/style.scss
> +    @media screen and (max-width: 600px) {
ほんまはメディアクエリはSassの機能でmixinにしたほうがいい
あとブレイクポイントは変数管理すべき

2024-05-22 09:07 UTC, alpaca1231 commented on css/style.scss
> +      height: calc(100vh - 60px);
この60pxって他の人や後から見た時にどういう数字かがぱっと見でわからないから
コメントで補足しておいたほうがいいと思った

2024-05-22 09:07 UTC, alpaca1231 commented on index.html
> +              テキストテキストテキストテキストテキストテキストテキスト<br />
これは豆知識やけどHTML5では`<br>`要素のスラッシュは不要になったんやけどフォーマッター（保存したときにコードを綺麗に整えてくれるやつ）が一律で付与してるだけやつね

2024-05-22 10:10 UTC, hiroakioike commented on css/style.scss
> +}
a {
  text-decoration: none;
}
→リンク表示の際にデフォルトで下線が出るなどの仕様を適用しないため

img {
  max-width: 100%;
}
→画像が画面のサイズ変更で不自然に引き伸ばされたりするのを防ぐため

li {
  list-style: none;
｝
→リスト表示の際にデフォルトでマーカーが出るなどの使用を適用しないため

2024-05-22 10:24 UTC, hiroakioike commented on css/style.scss
> +          }
first-childの位置を変更しました

2024-05-22 21:01 UTC, hiroakioike commented on css/style.scss
> +    @media screen and (max-width: 600px) {
mixinとブレイクポイント調べて書いてみました
煩雑かもですが自分用にコメントも書いてます

2024-05-23 01:32 UTC, alpaca1231 approved these changes
![LGTM](https://image.lgtmoon.dev/241923)

2024-05-28 00:26 UTC, merged